// Code generated by mockery v2.43.2. DO NOT EDIT.

package tnkbroker

import mock "github.com/stretchr/testify/mock"

// mockStopOrdersServiceClient is an autogenerated mock type for the stopOrdersServiceClient type
type mockStopOrdersServiceClient struct {
	mock.Mock
}

// newMockStopOrdersServiceClient creates a new instance of mockStopOrdersServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStopOrdersServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStopOrdersServiceClient {
	mock := &mockStopOrdersServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
