// Code generated by mockery v2.43.2. DO NOT EDIT.

package tnkbroker

import mock "github.com/stretchr/testify/mock"

// mockInstrumentServiceClient is an autogenerated mock type for the instrumentServiceClient type
type mockInstrumentServiceClient struct {
	mock.Mock
}

// newMockInstrumentServiceClient creates a new instance of mockInstrumentServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockInstrumentServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockInstrumentServiceClient {
	mock := &mockInstrumentServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
