// Code generated by mockery v2.43.2. DO NOT EDIT.

package tnkbroker

import mock "github.com/stretchr/testify/mock"

// mockMarketDataServiceClient is an autogenerated mock type for the marketDataServiceClient type
type mockMarketDataServiceClient struct {
	mock.Mock
}

// newMockMarketDataServiceClient creates a new instance of mockMarketDataServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMarketDataServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMarketDataServiceClient {
	mock := &mockMarketDataServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
